### ISSUE TITLE
Data Loading with Modin fails with Ray Client

### ISSUE THREAD

**Issue by amogkam** [ray-project/xgboost_ray#109]
Running `simple_modin.py` fails when used with Ray Client

```
$ python simple_modin.py --server-address localhost:50051
Traceback (most recent call last):
  File "simple_modin.py", line 103, in <module>
    main(args.cpus_per_actor, args.num_actors)
  File "simple_modin.py", line 37, in main
    modin_df = from_partitions(partitions, axis=0)
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/modin/distributed/dataframe/pandas/partitions.py", line 148, in from_partitions
    parts = np.array([[partition_class(partition)] for partition in partitions])
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/modin/distributed/dataframe/pandas/partitions.py", line 148, in <listcomp>
    parts = np.array([[partition_class(partition)] for partition in partitions])
  File "/Users/amog/dev/ray/lib/python3.8/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 27, in __init__
    assert type(object_id) is ray.ObjectRef
AssertionError
```

Looks like this is a modin issue though...

**Comment by amogkam** [comment]
This has been fixed with modin 0.10.0
