### ISSUE TITLE
[Autoscaler] Cluster not autoscaling

### ISSUE THREAD

**Issue by amogkam** [ray-project/xgboost_ray#11]
I have a cluster with a single head node with 64 CPUs and a single worker node with 4 CPUs, for a total of 68 CPUs. 

I am running examples/simple.py with 100 workers, each using 1 CPU on this cluster. Since there are more workers than num CPUs, I would expect the cluster to autoscale and add more nodes, but that's not the case. Instead I see a bunch of warnings of many Python workers being created:

```
2020-11-23 10:27:00,256	WARNING worker.py:1050 -- WARNING: 1062 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
2020-11-23 10:27:00,307	WARNING worker.py:1050 -- WARNING: 1062 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
2020-11-23 10:27:00,328	WARNING worker.py:1050 -- WARNING: 1062 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.

Increase to 200 actors, still not autoscaling triggered
Traceback (most recent call last):
  File "/root/simple.py", line 47, in <module>
    main()
  File "/root/simple.py", line 37, in main
    num_boost_round=100,)
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 475, in train
    **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 334, in _train
    ray.get(wait_load)
  File "/root/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1399, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): ray::RayXGBoostActor.load_data() (pid=2832, ip=172.31.27.185)
  File "python/ray/_raylet.pyx", line 425, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 426, in ray._raylet.execute_task
  File "/root/anaconda3/lib/python3.7/site-packages/ray/memory_monitor.py", line 132, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node ip-172-31-27-185 is used (14.82 / 15.35 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
314	0.15GiB	ray::RayXGBoostActor
580	0.15GiB	ray::RayXGBoostActor
531	0.15GiB	ray::RayXGBoostActor
341	0.15GiB	ray::RayXGBoostActor
413	0.15GiB	ray::RayXGBoostActor
662	0.15GiB	ray::RayXGBoostActor
511	0.15GiB	ray::RayXGBoostActor
312	0.15GiB	ray::RayXGBoostActor
406	0.15GiB	ray::RayXGBoostActor
472	0.15GiB	ray::RayXGBoostActor

In addition, up to 0.03 GiB of shared memory is currently being used by the Ray object store.
```
Here is the YAML that I am using:
```
cluster_name: amog_xgboost_scale
min_workers: 1
max_workers: 200
initial_workers: 1
autoscaling_mode: default
docker:
    image: 'anyscale/ray-ml:latest'
    container_name: ray_container
    pull_before_run: false
    run_options:
        - --privileged
        - --shm-size=510000000000
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    cache_stopped_nodes: false
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/amog-anyscale.pem
head_node:
    InstanceType: r5.16xlarge
    ImageId: ami-05ac7a76b4c679a79
    KeyName: amog-anyscale
worker_nodes:
    InstanceType: m5.xlarge
    ImageId: ami-05ac7a76b4c679a79
    KeyName: amog-anyscale
    InstanceMarketOptions:
        MarketType: spot
        
initialization_commands: []
setup_commands:
    - echo "hello"
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - pip install dask distributed xgboost s3fs
head_setup_commands: 
    - pip install -U git+https://github.com/ray-project/xgboost_ray@master#xgboost_ray
worker_setup_commands:
    - pip install -U git+https://github.com/ray-project/xgboost_ray@master#xgboost_ray
head_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=500000000000 --resources='{\"actor_cpus\": 0}'"
worker_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --resources='{\"actor_cpus\": 4}'"
```
Given the many warnings about a large number of Python workers being created and all the CPUs are being used, I believe the autoscaler should automatically add new nodes to the cluster.

Note that the OOM happened once, but I was not able to reproduce it again.

Interestingly, if I increase min_workers and initial_workers to 100, and run again with 700 actors, I am seeing the cluster autoscale to 200 nodes.

**Comment by amogkam** [comment]
Closing this since I can't reproduce on latest master. The cluster is correctly autoscaling (though it is slow).
