### ISSUE TITLE
RuntimeError: Tune is not installed, so `get_tune_resources` is not supported. You can install Ray Tune via `pip install ray[tune]`.

### ISSUE THREAD

**Issue by ksneab7** [ray-project/xgboost_ray#313]
### Problem
When running the example code for ray.tune integration in the readme,
The script successfully exectures `from ray import tune` but fails on the line `resources_per_trial=ray_params.get_tune_resources())`
I think this is due to the `TUNE_INSTALLED` global set in the `xgboost_ray/tune.py` file.

It seems that line 15 in that script (`from ray.tune import is_session_enabled`) is failing due to ray.tune not having that attribute.

### Steps to reproduce:
in this [section of the readme](https://github.com/ray-project/xgboost_ray?tab=readme-ov-file#hyperparameter-tuning)

### Error
```
Traceback (most recent call last):
  File "./testing_ray_data_load.py", line 46, in <module>
    resources_per_trial=ray_params.get_tune_resources())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/xgboost_ray/main.py", line 484, in get_tune_resources
    return _get_tune_resources(
           ^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/xgboost_ray/tune.py", line 180, in _get_tune_resources
    raise RuntimeError(
RuntimeError: Tune is not installed, so `get_tune_resources` is not supported. You can install Ray Tune via `pip install ray[tune]`.
```

**Comment by littlethumb123** [comment]
Came across the same issue and reinstall Ray didn't help.

**Comment by aditanase** [comment]
I am hitting this as well, trying to pre-install the ML libs in a docker image using pip / requirements.txt, on top of the default ray image.

Here's the minimal input that I am using:
```
pyarrow>=19.0.1
ray[data,serve,train,tune]==2.43.0
lightgbm-ray==0.1.9
xgboost-ray==0.1.19
scikit-learn==1.6.1
```

I confirmed that the dependencies made it in the image by running `pip list`.
Not sure what to try next.

**Comment by NinaHerrmann** [comment]
Same problem. I tried to trace back the problem but could not find a fast fix.

`from ray.tune import is_session_enabled` 

(tune.py l.15) fails but even if this is outcommented, another import fails

```python
from ray.tune.integration.lightgbm import (
    TuneReportCheckpointCallback as OrigTuneReportCheckpointCallback,
)
```

If there is no chance that this can get fixed soon I might take a look - but as I am not to  experienced with python packages
(3.13)
