### ISSUE TITLE
AttributeError: /root/anaconda3/lib/libxgboost.so: undefined symbol: XGDMatrixSetDenseInfo 

### ISSUE THREAD

**Issue by KangTomwk** [ray-project/xgboost_ray#62]
When running examples/simple.py again, the following error appears：
```
RayTaskError(AttributeError)              Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py in _train(params, dtrain, evals, ray_params, cpus_per_actor, gpus_per_actor, _training_state, *args, **kwargs)
    877             ready, not_ready = ray.wait(not_ready, timeout=0)
--> 878             ray.get(ready)
    879         # Once everything is ready

~/anaconda3/lib/python3.8/site-packages/ray/worker.py in get(object_refs, timeout)
   1378                 if isinstance(value, RayTaskError):
-> 1379                     raise value.as_instanceof_cause()
   1380                 else:
RayTaskError(AttributeError): ray::RayXGBoostActor.train() (pid=99109, ip=10.3.69.185)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py", line 438, in train
    self.load_data(dtrain)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py", line 416, in load_data
    matrix = _get_dmatrix(data, param)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py", line 242, in _get_dmatrix
    matrix = xgb.DMatrix(**param)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 509, in __init__
    self.set_info(label=label, weight=weight, base_margin=base_margin)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 422, in inner_f
    return f(**kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 530, in set_info
    self.set_label(label)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 659, in set_label
    dispatch_meta_backend(self, label, 'label', 'float')
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost/data.py", line 676, in dispatch_meta_backend
    _meta_from_numpy(data, name, dtype, handle)
  File "/root/anaconda3/lib/python3.8/site-packages/xgboost/data.py", line 600, in _meta_from_numpy
    _check_call(_LIB.XGDMatrixSetDenseInfo(
  File "/root/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/root/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /root/anaconda3/lib/libxgboost.so: undefined symbol: XGDMatrixSetDenseInfo

The above exception was the direct cause of the following exception:

RayActorError                             Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py in train(params, dtrain, num_boost_round, evals, evals_result, additional_results, ray_params, _remote, *args, **kwargs)
   1142         try:
-> 1143             bst, train_evals_result, train_additional_results = _train(
   1144                 params,
~/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py in _train(params, dtrain, evals, ray_params, cpus_per_actor, gpus_per_actor, _training_state, *args, **kwargs)
    903 
--> 904         raise RayActorError from exc
    905 
RayActorError: The actor died unexpectedly before finishing this task.
The above exception was the direct cause of the following exception:
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-6af09b0f80d5> in <module>
     76         ray.init(address="10.3.69.185:58043")
     77 
---> 78     main(args.cpus_per_actor, args.num_actors)

<ipython-input-1-6af09b0f80d5> in main(cpus_per_actor, num_actors)
     29 
     30     # Train the classifier
---> 31     bst = train(
     32         params=xgboost_params,
     33         dtrain=train_set,
~/anaconda3/lib/python3.8/site-packages/xgboost_ray/main.py in train(params, dtrain, num_boost_round, evals, evals_result, additional_results, ray_params, _remote, *args, **kwargs)
   1212                 queue, stop_event = _create_communication_processes()
   1213             else:
-> 1214                 raise RuntimeError(
   1215                     f"A Ray actor died during training and the maximum number "
   1216                     f"of retries ({max_actor_restarts}) is exhausted."
RuntimeError: A Ray actor died during training and the maximum number of retries (1) is exhausted.
```
The environment version is as follows：
python version ==3.8.5
ray version == 1.2.0
xgboost == 1..3.3

Do you know the reason?？？

**Comment by richardliaw** [comment]
Maybe related to https://github.com/dmlc/xgboost/issues/3389 ?

**Comment by richardliaw** [comment]
@KangTomwk have you taken look at the above references?
