### ISSUE TITLE
Is there's a way to set remote ray cluster address?

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/xgboost_ray#77]
I am new to ray community and I plan to run a XGBoost example to a remote cluster but can not find documentation. 

Seems following methods use `ray.init()` directly without remote options. 

https://github.com/ray-project/xgboost_ray/blob/256fb55c2956192a303e9f8dc6a430bedee0ba4a/xgboost_ray/main.py#L1048-L1049

Should I manually do `ray.init(addresses={remove_addr})` or `ray.util.connect({remote})` in the code snippet?  In this way, xgboost_ray package will think `ray.is_initialized()` is true and skip initialization?

**Comment by Jeffwan** [comment]
Here's my code 

```
from xgboost_ray import RayDMatrix, RayParams, train
from sklearn.datasets import load_breast_cancer
import os
import ray

HEAD_SERVICE_IP_ENV = "EXAMPLE_CLUSTER_RAY_HEAD_SERVICE_HOST"
HEAD_SERVICE_CLIENT_PORT_ENV = "EXAMPLE_CLUSTER_RAY_HEAD_SERVICE_PORT_CLIENT"

head_service_ip = os.environ[HEAD_SERVICE_IP_ENV]
client_port = os.environ[HEAD_SERVICE_CLIENT_PORT_ENV]
ray.util.connect(f"{head_service_ip}:{client_port}")

train_x, train_y = load_breast_cancer(return_X_y=True)
train_set = RayDMatrix(train_x, train_y)
evals_result = {}
bst = train(
    {
        "objective": "binary:logistic",
        "eval_metric": ["logloss", "error"],
    },
    train_set,
    evals_result=evals_result,
    evals=[(train_set, "train")],
    verbose_eval=False,
    ray_params=RayParams(
        num_actors=2,
        cpus_per_actor=1))
bst.save_model("model.xgb")
print("Final training error: {:.4f}".format(
    evals_result["train"]["error"][-1]))
```

The code complain xgboost_ray can not find. I do check my container env and it's there. 

```
--2021-04-07 16:14:34--  https://gist.githubusercontent.com/Jeffwan/0da1e009cf3083d30bbfd7fe6c4e02fc/raw/5dc3f8b4df0d689ff7f6f447b139eb77bd932a11/ray-xgboost.py
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 941 [text/plain]
Saving to: ‘ray-xgboost.py’

     0K                                                       100% 24.7M=0s

2021-04-07 16:14:34 (24.7 MB/s) - ‘ray-xgboost.py’ saved [941/941]

Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: No module named 'xgboost_ray'"
	debug_error_string = "{"created":"@1617837276.220074000","description":"Error received from peer ipv4:10.99.2.122:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: No module named 'xgboost_ray'","grpc_status":2}"
>
Traceback (most recent call last):
  File "ray-xgboost.py", line 28, in <module>
    cpus_per_actor=1))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1047, in train
    **kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/remote_function.py", line 104, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/remote_function.py", line 209, in _remote
    name=name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 73, in client_mode_convert_function
    return client_func._remote(in_args, in_kwargs, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 106, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 283, in remote
    return return_refs(ray.call_remote(self, *args, **kwargs))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 96, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 289, in call_remote
    task = instance._prepare_client_task()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 289, in _prepare_client_task
    task = self.remote_stub._prepare_client_task()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 127, in _prepare_client_task
    self._ensure_ref()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 124, in _ensure_ref
    self._func, client_ref_id=self._client_side_ref.id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 45, in put
    return self.worker.put(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 233, in put
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 233, in <listcomp>
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 250, in _put
    resp = self.data_client.PutObject(req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 149, in PutObject
    resp = self._blocking_send(datareq)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 109, in _blocking_send
    "Cannot send request due to data channel "
ConnectionError: Cannot send request due to data channel shutting down. Request: req_id: 3
put {
  data: "\200\005\225Q\003\000\000\000\000\000\000\214\033ray.cloudpickle.cloudpickle\224\214\r_builtin_type\224\223\224\214\nLambdaType\224\205\224R\224(h\002\214\010CodeType\224\205\224R\224(K\000K\000K\005K\006K\037C(i\000}\002i\000}\003t\000|\000\210\000|\002|\003d\001\234\003|\001\227\002\216\001}\004|\004|\002|\003f\003S\000\224N\214\017num_boost_round\224\214\014evals_result\224\214\022additional_results\224\207\224\206\224\214\005train\224\205\224(\214\004args\224\214\006kwargs\224\214\r_evals_result\224\214\023_additional_results\224\214\003bst\224t\224\214C/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py\224\214\010_wrapped\224M\003\004C\022\000\002\004\001\004\001\002\001\002\001\002\001\002\001\006\001\010\001\224h\n\205\224)t\224R\224}\224(\214\013__package__\224\214\013xgboost_ray\224\214\010__name__\224\214\020xgboost_ray.main\224\214\010__file__\224\214C/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py\224uNNh\000\214\020_make_empty_cell\224\223\224)R\224\205\224t\224R\224\214 ray.cloudpickle.cloudpickle_fast\224\214\022_function_setstate\224\223\224h)}\224}\224(h h\030\214\014__qualname__\224\214\027train.<locals>._wrapped\224\214\017__annotations__\224}\224\214\016__kwdefaults__\224N\214\014__defaults__\224N\214\n__module__\224h!\214\007__doc__\224N\214\013__closure__\224h\000\214\n_make_cell\224\223\224K\n\205\224R\224\205\224\214\027_cloudpickle_submodules\224]\224\214\013__globals__\224}\224h\017h!h\017\223\224su\206\224\206R0."
  client_ref_id: "\314\275\231\367\316\300\332E@\206G*u\'\020S|"
}

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 90, in _data_main
    raise e
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 64, in _data_main
    for response in resp_stream:
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: No module named 'xgboost_ray'"
	debug_error_string = "{"created":"@1617837276.220074000","description":"Error received from peer ipv4:10.99.2.122:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: No module named 'xgboost_ray'","grpc_status":2}"
>

```


```
>>> import xgboost_ray
>>> xgboost_ray.__file__
'/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/__init__.py'
```

**Comment by richardliaw** [comment]
You should try building an image with the xgboost_ray dependency for now! We will have better support for this in a couple releases.

**Comment by Jeffwan** [comment]
Thanks. I actually forget to change head node image to the one with xgboost_ray package.
After changing the image, it shows following errors. 

```
 k logs -f ray-xgboostxfpdd-qnqlm
--2021-04-08 10:46:14--  https://gist.githubusercontent.com/Jeffwan/0da1e009cf3083d30bbfd7fe6c4e02fc/raw/5dc3f8b4df0d689ff7f6f447b139eb77bd932a11/ray-xgboost.py
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 941 [text/plain]
Saving to: ‘ray-xgboost.py’

     0K                                                       100% 1.24M=0.001s

2021-04-08 10:46:14 (1.24 MB/s) - ‘ray-xgboost.py’ saved [941/941]

WARNING: 3 PYTHON workers have been started on a node of the id: 38e179daeb3e30b5f4cece05c69c2c6645452a8203fb57b7017a8c0e and address: 10.1.0.142. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
Traceback (most recent call last):
  File "ray-xgboost.py", line 28, in <module>
    cpus_per_actor=1))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/xgboost_ray/main.py", line 1047, in train
    **kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 35, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 198, in get
    res = self._get(obj_ref, op_timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 212, in _get
    data = self.data_client.GetObject(req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 143, in GetObject
    resp = self._blocking_send(datareq)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 109, in _blocking_send
    "Cannot send request due to data channel "
ConnectionError: Cannot send request due to data channel shutting down. Request: req_id: 5
get {
  id: "\263q]\252\314\010\304Z\377\377\377\377\377\377\377\377\377\377\377\377\001\000\000\000\001\000\000\000"
  timeout: 2.0
}
```

**Comment by richardliaw** [comment]
Can you try adding a `ray.init(address="auto")` in your script, instead of using Ray client?

**Comment by Jeffwan** [comment]
@richardliaw 

Thanks. `ray.init(address="auto")` works but only if I run it inside head pod. My case is to submit ray job to a remote cluster (Ray cluster on k8s.)

Application may be trigger in kubernetes (talks to cluster ip of head service) or somewhere else (talks to Load balancer of head service)

However, seems `ray.util.connect(k8s_cluster_ip:10001)` or `ray.util.connect(load_balancer:10001)` doesn't work as expected.

**Comment by Jeffwan** [comment]
I delete all environments and reinstall everything with nightly images and it's working now. Remote submission using client mode works. Thanks for the help and I will close the issue.
